### ISSUE TITLE
Error sending message to Synology Chat

### ISSUE THREAD

**Issue by loudsun1997** [Xueheng-Li/SynologyChatbotGPT#3]
I am experiencing an issue with sending a message to Synology Chat using the provided webhook. When I attempt to send a message, I receive the following error:

"Error sending message to Synology Chat: HTTPSConnectionPool(host='192.168.1.123', port=5001): Max retries exceeded with url: /webapi/entry.cgi?api=SYNO.Chat.External&method=chatbot&version=2&token=%22TK0NOzhlYGw5qVv0Z4qV1MZvyMheKEAo2iftHrSwqUlZ99ZNBqqbCwUN9WLft3DO%22 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))"

I have attempted to set the "verify" parameter to "False" in my code, but this has not resolved the issue. Instead, I received an InsecureRequestWarning with the following message:

"InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.123'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings"

Although I received a warning that an unverified HTTPS request was being made, the HTTP request came back with a status code of 200.

I am still not able to receive any messages back from the chatbot. Can you please provide assistance in resolving this issue?

**Comment by vivagonna** [comment]
I worked this around by using the synology DDNS host name instead of IP. 
First I deleted the bot from synology chat, then log off and log into synology chat again using my synology DDNS address, instead of ip. Re-create a bot, now INCOMING_WEBHOOK_URL generated by Synology chat will contain your DDNS address. Update setting.py with new webhood URL and Token, it works perfectly.
